services:
  - type: web
    name: web-scrape
    runtime: node
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome"
